server:
  port: 80
spring:
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/ # 跳转页面的前缀
    suffix: .html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.100:3306/miaosha?serverTimezone=GMT%2B8
    username: root
    password: 7292183hkx
  redis:
    host: 192.168.0.100
    port: 6379
    timeout: 10
    password: root
    jedis:
      pool:
        max-active: 1000
        max-idle: 500
        max-wait: 500
  resources:
    cache:
      period: 3600 # 缓存时间
    chain:
      enabled: true
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
    listener:
      simple:
        concurrency: 10 # 消费者数量
        max-concurrency: 10
        prefetch: 1 # 每次取几个
        auto-startup: true
        default-requeue-rejected: true # 拒绝策略 重新排队
    template:
      retry:
        enabled: true # 队列满 放不进去则重试
        initial-interval: 1000 # 多少ms后重试
        max-attempts: 3 # 重试次数
        max-interval: 10000 # 3次之间的间隔
        multiplier: 1.0 # 等待时间是否逐步延长 如果为2  则 第一次10s 第二次 20s 第三次40s


mybatis:
  type-aliases-package: com.imooc.miaosha.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
